site_name: "Nemesis: Lockdown - Instrukcja"
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
#    - navigation.tabs
#    - navigation.tabs.sticky
#    - navigation.sections
    - navigation.expand
    - navigation.path
markdown_extensions:
  - toc:
      permalink: true
nav:
  - Strona Główna: index.md
  - Dostępne akcje: podstawowa-wersja/podstawowa-wersja-akcje.md
  - Faza graczy:
      - Czym jest faza graczy?: podstawowa-wersja/faza-graczy/faza-graczy.md
      - 1. Dobieranie kart akcji: podstawowa-wersja/faza-graczy/dobieranie-kart-akcji/dobieranie-kart-akcji.md
      - 2. Przekazanie żetonu gracza: podstawowa-wersja/faza-graczy/przekazanie-zetonu-gracza/przekazanie-zetonu-gracza.md
      - 3. Tury graczy: podstawowa-wersja/faza-graczy/tury-graczy/tury-graczy.md
  - Faza wydarzeń:
    - 4. Wystrzelenie kapsuł SWC: podstawowa-wersja/faza-wydarzen/wystrzelenie-kapsul-swc/wystrzelenie-kapsul-swc.md
    - 5. Tor czasu: podstawowa-wersja/faza-wydarzen/tor-czasu/tor-czasu.md
    - 6. Usunięcie znaczników szmerów: podstawowa-wersja/faza-wydarzen/usuniecie-znacznikow-szmerow/usuniecie-znacznikow-szmerow.md
    - 7. Atak nocnego łowcy: podstawowa-wersja/faza-wydarzen/atak-nocnego-lowcy/atak-nocnego-lowcy.md
    - 8. Skutki pożaru dla łowcy: podstawowa-wersja/faza-wydarzen/skutki-pozaru-dla-lowcy/skutki-pozaru-dla-lowcy.md
    - 9. Karta wydarzenia: podstawowa-wersja/faza-wydarzen/karta-wydarzenia/karta-wydarzenia.md
    - 10. Kolonia nocnych łowców: podstawowa-wersja/faza-wydarzen/kolonia-nocnych-lowcow/kolonia-nocnych-lowcow.md
    - 11. Koniec rundy: podstawowa-wersja/faza-wydarzen/koniec-rundy/koniec-rundy.md