site_name: "Nemesis: Lockdown - Instrukcja"
theme:
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7


        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections
    - navigation.expand
    - navigation.path
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Strona Główna: index.md
  - Podstawowe info:
      - Gdzie zaczyna dana postać: podstawowe-informacje/gdzie-zaczynam.md
      - Plansza Laboratorium: podstawowe-informacje/plansza-laboratorium.md
      - Koniec gry: podstawowe-informacje/koniec-gry.md
      - Warunki zwycięstwa: podstawowe-informacje/warunki-zwyciestwa.md
  - Rzeczy powtarzalne:
      - Rzut na szmery: powtarzalne/rzut-na-szmery.md
      - Niebezpieczeństwo: powtarzalne/niebezpieczenstwo.md
      - Spotkanie Nocnego Łowcy: powtarzalne/atak-nocnego-lowcy.md
      - Umieszczenie pożaru: powtarzalne/umieszczam-pozar.md
      - Umieszczenie awarii: powtarzalne/umieszczam-awarie.md
      - Akcje:
        - Podstawowe info: akcje-graczy/akcje-podstawowe-info.md
        - Ruch: akcje-graczy/akcja-ruch.md
        - Przeszukanie: akcje-graczy/akcja-przeszukanie.md
        - Akcje pomieszczeń: pomieszczenia/lista-pomieszczen.md
        - Akcje kart akcji: akcje-graczy/akcja-karty-akcji.md
        - Akcje kart przedmiotów: akcje-graczy/akcja-karty-przedmiotow.md
        - Podnieś ciężki obiekt: akcje-graczy/akcja-podnies-ciezki-obiekt.md
        - Upuść przedmiot: akcje-graczy/akcja-upusc-przedmiot.md
        - Handel: akcje-graczy/akcja-handel.md
        - Zrób przedmiot: akcje-graczy/akcja-zrob-przedmiot.md
        - Walka: akcje-graczy/akcja-walka.md
        - Niszczenie jaj: akcje-graczy/akcja-niszczenie-jaj.md
        - Ucieczka: akcje-graczy/akcja-ucieczka.md
        - Komputer: akcje-graczy/akcja-komputer.md
        - Skanowanie kart skażenia: akcje-graczy/akcja-skanowanie-kart.md
        - Pomieszczenia: pomieszczenia/lista-pomieszczen.md
  - Faza graczy:
    - Czym jest faza graczy?: faza-graczy/faza-graczy.md
    - 1. Dobieranie kart akcji: faza-graczy/01-dobieranie-kart-akcji.md
    - 2. Przekazanie żetonu gracza: faza-graczy/02-przekazanie-zetonu-gracza.md
    - 3. Tury graczy: faza-graczy/03-tury-graczy.md
  - Faza wydarzeń:
    - Czym jest faza wydarzeń: faza-wydarzen/faza-wydarzen.md
    - 4. Wystrzelenie kapsuł SWC: faza-wydarzen/04-wystrzelenie-kapsul-swc.md
    - 5. Tor czasu: faza-wydarzen/05-tor-czasu.md
    - 6. Usunięcie znaczników szmerów: faza-wydarzen/06-usuniecie-znacznikow-szmerow.md
    - 7. Atak nocnego łowcy: faza-wydarzen/07-atak-nocnego-lowcy.md
    - 8. Skutki pożaru dla łowcy: faza-wydarzen/08-skutki-pozaru-dla-lowcy.md
    - 9. Karta wydarzenia: faza-wydarzen/09-karta-wydarzenia.md
    - 10. Kolonia nocnych łowców: faza-wydarzen/10-kolonia-nocnych-lowcow.md
    - 11. Koniec rundy: faza-wydarzen/11-koniec-rundy.md