site_name: "Nemesis: Lockdown - Instrukcja"
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
#    - navigation.tabs
#    - navigation.tabs.sticky
#    - navigation.sections
    - navigation.expand
    - navigation.path
markdown_extensions:
  - toc:
      permalink: true
nav:
  - Strona Główna: index.md
  - Dostępne akcje: podstawowa-wersja/podstawowa-wersja-akcje.md
  - Faza wydarzeń:
    - 4. Wystrzelenie kapsuł SWC: podstawowa-wersja/faza-wydarzen/wystrzelenie-kapsul-swc/wystrzelenie-kapsul-swc.md
    - 5. Tor czasu: podstawowa-wersja/faza-wydarzen/tor-czasu/tor-czasu.md
    - 10. Kolonia nocnych łowców: podstawowa-wersja/faza-wydarzen/kolonia-nocnych-lowcow/kolonia-nocnych-lowcow.md